### ISSUE TITLE
I think library h files need to be in root of the lib not in utility directory

### ISSUE THREAD

**Issue by djmerrill** [NVSL/gadgetron-software-libraries#2]
arduino cant seem to find them in utility/

**Comment by jgarzagu** [comment]
We can't have too many .h files in the root of the lib because they can conflict with other libraries. 
To add a library (e.g foo.h) add it utility/foo.h and then add it to Gadgetron.h and It should work.

**Comment by djmerrill** [comment]
Fixed with new style include in test program generation.
