### ISSUE TITLE
Need to push new version to Arduino cloud

### ISSUE THREAD

**Issue by djmerrill** [NVSL/gadgetron-software-libraries#3]
Need to make sure the latest version is what we download from Arduino.

**Comment by jgarzagu** [comment]
Released version 1.0.1 of gadgetron-software-libraries. 
I will check it tomorrow if it got updated in Arduino server.

**Comment by jgarzagu** [comment]
Version 1.0.1 is now on the Arduino server.

Best, 
Jorge
