### ISSUE TITLE
An older version of the Song/Buzzer library is being used

### ISSUE THREAD

**Issue by MichaelMGonzalez** [NVSL/gadgetron-software-libraries#4]

**Comment by djmerrill** [comment]
I tried changing it over in a student’s code but it seemed to have the same behavior.

It gets stuck on  display.begin(0x70);

Any ideas?

**Comment by MichaelMGonzalez** [comment]
Is this in regards to the LED Arrays?

The LED Arrays will work when defined as:

Adafruit_8x8matrix display = Adafruit_8x8matrix();

...

void setup() {
   ...
   display.setup(); // begin is not required
}

**Comment by MichaelMGonzalez** [comment]
Or is the issue you're talking about in regards to the instructions I left to patch the song library here?

https://sites.google.com/a/eng.ucsd.edu/robot-parade/weekly/programming-your-robot

**Comment by djmerrill** [comment]
Led array. Tried your fix but it didn't work.
